atmo/coordinator/coordinator.go, example-project/Directive.yaml, example-project/cache-get/.runnable.yaml, example-project/cache-get/Cargo.lock, example-project/cache-get/Cargo.toml, example-project/cache-get/src/lib.rs, example-project/cache-set/.runnable.yaml, example-project/cache-set/Cargo.lock, example-project/cache-set/Cargo.toml, example-project/cache-set/src/lib.rs, example-project/fetch-test/Cargo.lock, example-project/fetch-test/Cargo.toml, example-project/fetch-test/src/lib.rs, example-project/helloworld-rs/.runnable.yml, example-project/helloworld-rs/Cargo.lock, example-project/helloworld-rs/Cargo.toml, example-project/helloworld-rs/src/lib.rs, example-project/modify-url/.runnable.yml, example-project/modify-url/Cargo.lock, example-project/modify-url/Cargo.toml, example-project/modify-url/src/lib.rs, go.mod, go.sum, release/version.go, vendor/github.com/suborbital/hive-wasm/request/request.go, vendor/github.com/suborbital/hive-wasm/wasm/ffi_environment.go, vendor/github.com/suborbital/hive-wasm/wasm/wasmrunnable.go, vendor/modules.txt
Atmo now uses hive-wasm v0.4.0 and uses its new CoordinatedRequest type along with the helpers and API version that comes with it.
Example project Runnables have been updated to use API 0.4.0.
=> Update hive-wasm and all example project Runnables

Makefile, atmo/coordinator/sequence.go, atmo/coordinator/sequence_test.go, directive/directive.go, directive/directive_test.go, example-project/Directive.yaml
The `with` clause becomes a map, and the unneeded parsing and caching of the old array-style is all removed.
=> Optimize and update Directive

Makefile, atmo/atmo.go, atmo/options/options.go, docs/SUMMARY.md, docs/usage/deploying-atmo.md, main.go
This PR allows Atmo to 'wait' for a bundle to exist on disk and startup when it does, rather than erroring out if no bundle exists.
This is to support easier K8s deployments, and can be tried out here: https://github.com/suborbital/atmo-k8s-helm
=> Add 'wait' ability

docs/usage/building-a-bundle.md, docs/usage/error-handling.md
- Remove usage of defunct `--bundle` flag for `subo build`
- Mention that error codes must be valid HTTP response status codes. This was an issue I encountered which was causing `atmo` to panic when serving invalid codes. Happy to revert this particular change if you think it doesn't warrant mentioning.
=> Small improvements to documentation

Makefile, atmo/appsource/appsource.go, atmo/appsource/bundlesource.go, atmo/appsource/headlessbundlesource.go, atmo/atmo.go, atmo/coordinator/coordinator.go, atmo/coordinator/coordinator_appstate.go, atmo/coordinator/sequence.go, atmo/options/options.go, bundle/load/load_bundle.go, directive/directive.go, docs/SUMMARY.md, docs/usage/headless.md, example-project/Directive.yaml, fqfn/fqfn.go, go.mod, go.sum, main.go, vendor/github.com/suborbital/vektor/vk/optionmodifiers.go, vendor/github.com/suborbital/vektor/vk/options.go, vendor/github.com/suborbital/vektor/vk/router.go, vendor/github.com/suborbital/vektor/vk/server.go, vendor/modules.txt
This implements 'headless' mode that causes Atmo to ignore the Directive and make each Runnable available at its own endpoint, using the FQFN as a URL.
Resolves #43
=> Headless mode

atmo/coordinator/executor/executor.go, atmo/coordinator/sequence.go, atmo/coordinator/sequence_single.go
Previously to the `autoscaling` work, all function executions happened through Atmo's internal Grav message bus. This was found to be less performant than just calling the Reactr instance directly instead (somewhat obvious in retrospect)
The autoscaling work added the `Executor` type, which is a facade over the two methods of executing a function (locally, by calling Reactr directly, or remotely by sending a message over the Grav bus), so that the most appropriate method would always be used.
This meant that functions executed on the local Reactr instance directly no longer had messages sent over the Grav bus to, for example, let a configured control-plane know that something had been executed.
This PR adds message sending back into the fray to restore the old functionality while still …
=> Send messages before and after local function execution

atmo/appsource/bundlesource.go, atmo/coordinator/coordinator_headlessauth.go
This PR modifies the headless auth middleware to skip auth if the request URL in question is not an FQFN, which in headless mode includes `/meta/metrics` and `/health`. All Runnables are accessed by full FQFN URL, so auth will continue to run on those requests.
=> Only run headless auth on Runnable endpoints

atmo/appsource/httpsource.go
This fixes a potential crash if `opts.Wait` is nil, and changes some logging around
=> HTTPSource improvements

go.mod, go.sum
@cohix Why didn't the old version disappear from the `go.mod`?
=> Upgrade to Reactr Beta-14

.github/workflows/sanity.yml, atmo/atmo.go, atmo/coordinator/coordinator.go, atmo/coordinator/coordinator_headlessauth.go, atmo/coordinator/executor/executor.go, atmo/coordinator/executor/executor_proxy.go, atmo/options/options.go, go.mod, go.sum
This allows a 'global' env token to be set when Atmo is in proxy mode. This allows atmo-proxy to authenticate the `FundRunnable` call to the control plane for all requests.
This PR also exposes capability configs on the executor and adds a build step to CI to ensure proxy mode can always be built.
=> feat(proxy): global environment token

.github/workflows/release.yml, .github/workflows/sanity.yml, .goreleaser.yml
Adds release workflow that runs GoReleaser, creating archives for atmo
and atmo-proxy on tagged releases.
=> Add goreleaser

atmo/coordinator/coordinator.go, atmo/coordinator/executor/executor.go, atmo/coordinator/executor/executor_proxy.go, atmo/options/options.go
This PR allows the user to set `ATMO_PEERS` to "force" Grav connections to specific peers.
Discovery is also still enabled, and will create connections in addition to the static peers
=> feat(coordinator): ability to define static peers for Grav connection

atmo/coordinator/coordinator_stream.go, atmo/coordinator/executor/executor.go, go.mod, go.sum
This updates Grav such that non-`message` formatted messages can be read off a stream without issue. It also ensures a consistent UUID is used for the message handling.
This PR also adds an early exit to `ConnectStaticPeers` which would cause an attempt to connect to a peer when none were configured, adding logging noise.
=> fix(streams): update Grav and use consistent UUID for stream handlers

atmo/coordinator/capabilities/capabilities.go
The check for database connections was comparing the ident and the namespace to the ident and version,
which can never be true.
Also related to this bug, the `userConfig` defined in capabilities from reactr is always defined by default.
As such, the check for `userConfig.DB != nil` always evaluated to true, overwriting the database defined
in connections.
Fixes: #166
=> fix(coordinator): Update connections check to check version instead of namespace

atmo/appsource/httpsource.go
We encountered a panic when the `resp` returned by `authedGet` is nil and then checking the status code.
=> fix(httpsource): nil check response when comparing status code

syncer/syncer.go
`GetModuleByName` acquires a read lock and then  calls `TenantOverview` which also acquires a ReadLock. 
`State` is called every second and acquires a WriteLock. 
If `GetModuleByName` acquires a ReadLock and State awaits a WriteLock before `TenantOverview` is called (within the GetModuleByName method) then State is awaiting GetModuleByName which called TenantOverview which is awaiting State. 
This change removes the need to call TenantOverview from within GetModuleByName remove the possibility for this deadlock.
=> fix(syncer): Fix GetModuleByName deadlock

auth/access.go, auth/authorizer_test.go, auth/cache.go, common/atomic.go, common/cache.go, common/cache_test.go, common/clock.go, common/error.go, go.mod, go.sum, options/options.go, server/coordinator/coordinator.go
without fix:  1.40s user 2.10s system 8% cpu 40.612 total
```bash
time (repeat 500 { curl -s -X POST  -H "Authorization: Bearer ${SUPER_CLIENT_TOKEN}" -d "hello"  http://localhost:8080/name/${IDENTIFIER}/default/${FUNCTION} > /dev/null})
( repeat 500; do; curl -s -X POST -H  -d "hello"  > /dev/null; done; )  1.40s user 2.10s system 8% cpu 40.612 total
```
With fix: 0.96s user 1.49s system 54% cpu 4.522 total
```bash
time (repeat 500 { curl -s -X POST  -H "Authorization: Bearer ${SUPER_CLIENT_TOKEN}" -d "hello"  http://localhost:8080/name/${IDENTIFIER}/default/${FUNCTION} > /dev/null})
( repeat 500; do; curl -s -X POST -H  -d "hello"  > /dev/null; done; )  0.96s user 1.49s system 54% cpu 4.522 total
```
Currently each request that comes in requires an additional trip to the control plane …
=> feat(auth): API Authorization Cache

.github/workflows/ci.yml, Dockerfile
The Go mods file shows this as a 1.19, but we don't test builds or build
artifcates (binaries and containers) on 1.19.
This commit changes that.
Also updates `golangci-lint` to latest to ensure that it gets 1.19 support.
=> chore: Update CI to Go 1.19

.github/workflows/ci.yml, ops/Dockerfile-gci
Uses the Go version describe in the Go modules file instead of whatever is in the workflow.
Also enables the built in caching to setup-go.
=> chore: Use Go version from gomods

docker-compose-util.yaml, ops/Dockerfile-gci, ops/gci.sh, sat/Makefile, sat/docker-compose.yaml, sat/ops/Dockerfile-gci, sat/ops/gci.sh
golangci-lint can fix gci lint errors, and others.
=> chore: Use built in lint fix

.github/workflows/ci.yml
This should use the cache with the same ID as other jobs, rather than storing a similar one under the golang action.
=> chore: Use the setup-go cache over golangci-lint cache

Dockerfile
Adds a CMD stanza to the Dockerfile which ensures that Docker will start
the container with these arguments by default if not provided/overrode
by other runtimes (Kuberntes, compose, etc).
=> chore: Add CMD to Dockerfile

.github/renovate.json5
Previously only disabled mainline otel updates. This commit disables updates from contrib as well.
Related to #291
=> chore: Disable otel updates for both otel, otel-contrib

.subo.yml, changelogs/v0.5.1.md, e2core/release/version.go
E2Core Beta-5.1 adds command to the Docker image, allowing the container to start in server mode by default.
https://github.com/suborbital/e2core/compare/v0.5.0...rc-v0.5.1
=> chore: Release v0.5.1

e2core/auth/access.go, e2core/coordinator/coordinator.go, e2core/coordinator/coordinator_headlessauth.go, e2core/coordinator/coordinator_request.go, e2core/coordinator/coordinator_tracing.go, e2core/coordinator/coordinator_workflow.go, e2core/coordinator/health.go, e2core/coordinator/metrics.go, go.mod, go.sum, sat/sat/handler.go, sat/sat/worker_metrics.go
Updates vektor to v0.6.1
- Updates Middleware to be wrappable
- Updates handlers for new function signatures
- Replaces `vk.R` with `vk.RepondJSON` or `vk.RepondBytes`
=> feat: Update vektor and systemspec

e2core/auth/access.go, e2core/server/server.go
The hosted Admin feature flag logic was lost during the refactor, this PR brings it back.
There was also a small change to the tenant identifier format which removes the requirement of an environment prefix which is now reflected in the authorizer code. 
Future work: Add reverse look up from ref to plugin for admin enabled e2 core.
=> fix: Bring back capability to enable multi-tenant mode

e2core/auth/access.go
See also https://github.com/suborbital/se2/pull/1028
=> fix(auth): tenant api now hosted on api service

.github/workflows/ci.yml, .goreleaser.yml
Builds the binary on each commit, and only pushes artifacts on releases.
=> chore: Build binaries with gorelease on each commit

e2core/command/mod_start.go
Adds a flag `--http-port` to `e2core mod start`, to select the HTTP port the sat instance will be exposed on.
This is currently only possible by setting `HTTP_SAT_PORT` on the env, which works well enough but undocumented and not very discoverable.
=> feat: Add --http-port flag to e2core mod start

e2core/server/handlers.go, e2core/server/server.go
No issue
Add some more logging to get a better understanding of what's happening in e2core behind the scenes when executing a plugin by name.
=> chore(e2core): Add logger to e2core server

e2core/server/handlers.go, e2core/sourceserver/server.go
No issue
Every time e2core returns an http error, the underlying error will also be logged.
This means **every** `return echo.NewHTTPError()` call has a setinternal in the entire codebase.
=> chore(errors) All echo.NewHTTPErrors have a SetInternal attached to them

go.mod, go.sum, sat/engine2/runtime/instance/instance.go, sat/engine2/runtime/pool.go
No issue
Following the news about a critical vulnerability in wasmtime (https://github.com/bytecodealliance/wasmtime/security/advisories/GHSA-ff4p-7xrq-q5r8), this PR updates the version we use to not have that issue.
=> chore(wasmtime): Upgrade wasmtime to v7

docker-compose-util.yaml, e2core/backend/satbackend/command.go, e2core/backend/satbackend/exec/exec.go, e2core/backend/satbackend/orchestrator.go, e2core/backend/satbackend/watcher.go
Closes #426 
Syscall is dead, long live exec! I also vastly simplified the way creating subprocesses work. At a glance:
* instead of `syscall.ForkExec`, the way to start is `cmd.Start()`, which will asynchronously start a configured command
* no need for `syscall.procinfo`, because everything else was already assigned to the properties of the command struct
* no need to keep track of process ids, because the `exec.CommandWithContext` gets a context which has a cancel function with cause
* the terminate and scale down functionalities merely call the cancel functions for the running processes, which do not return errors. It is implied that everything will just work because we've moved the responsibility of keeping track of shutdown and whatnot to the go standard library
`syscall` package …
=> fix(e2core): Replace syscall

e2core/backend/satbackend/exec/exec.go, e2core/backend/satbackend/orchestrator.go, e2core/backend/satbackend/watcher.go
Related to #426 
This is a quality of life improvement that deals with crashed processes and recovery.
When using the `command.Start()` function call, the process starts in the background. We're supposed to use the `command.Wait()` to determine when either the process finished, or exited for some other reason.
This changeset accommodates collecting the wait functions, starts them for each sub process, and when they unblock, their ports are added to a `died` map, which will then be  removed automatically from watcher's bookkeeping.
I've tested this manually by:
1. creating an image for `e2core` using `make docker/dev`
2. starting up everything with se2's `docker compose up` (this is internal)
3. start following the logs with `docker compose logs e2core --follow` (this is internal)
4. …
=> fix(e2core): Deal with dead processes

e2core/server/server.go, e2core/sourceserver/bundle.go, sat/sat/sat.go
No issue
If we panic at any point when creating a new instance, this middleware should recover it
=> fix(e2core): Add the panic recovery middleware to our echoes
