suborbital/e2core

README.md

Hi there!
Found out about `Atmo` this morning and it's a sweet project. As I've been learning more I looked over this repo, and I saw two little typos in the README. Thought I'd go ahead and fix those while I was looking around.

Fixed two little typos in README

---

atmo/coordinator/coordinator.go
atmo/coordinator/sequence.go
go.mod
go.sum
vendor/github.com/suborbital/reactr/directive/directive.go
vendor/github.com/suborbital/reactr/request/request.go
vendor/github.com/suborbital/reactr/request/response.go
vendor/github.com/suborbital/reactr/rwasm/api_resp.go
vendor/github.com/suborbital/reactr/rwasm/ffi_environment.go
vendor/github.com/suborbital/reactr/rwasm/wasmrunnable.go
vendor/modules.txt

Makes the `resp::set_header` API function actually do its job!

Allow Runnables to set response headers

---

docs/SUMMARY.md
docs/getstarted.md
docs/introduction/building-and-running.md
docs/introduction/creating-a-project.md
docs/runnable-api/introduction.md

docs: Add basic project creation, building, and running instructions

---

docs/concepts/state.md
docs/getstarted/building-and-running.md
docs/usage/building-a-bundle.md
docs/usage/creating-handlers.md
docs/usage/foreach.md
example-project/as-graphql/package-lock.json

Atmo doc fixes here- I know we'll be replacing all examples with Typescript or another language, this is until that point.

Fix Atmo docs until 'Deploying Atmo'

---

README.md

Update logo and README

---

atmo/coordinator/capabilities/capabilities.go
atmo/coordinator/coordinator.go

- it is now called capabilities.Render()

Extract renderCapabilities() into capabilities pkg

---

README.md

Add 2 references to the External contributions (project link + blog post)

Add Atmo PostgreSQL demo + blog post

---

atmo/coordinator/executor/executor.go
atmo/coordinator/executor/executor_proxy.go
atmo/coordinator/sequence/sequence.go
directive/executable/executable.go

This change prevents concurrency issues when using Proxy mode

Move 'completed' field to Step containing type

---

directive/directive_test.go
directive/directive_validator.go

intended to close https://github.com/suborbital/subo/issues/53

Throw validation error on route conflicts (Subo #53)

---

atmo/appsource/httpsource.go

Previously, the HTTP appsource in headless mode would always return all runnables for all applications.
This PR adds a filter by ident to prevent incorrect runnables being returned when multiple applications exist.

fix(appsource): filter headless runnables by ident

---

atmo/release/version.go
changelogs/v0.4.4.md
docs/concepts/the-directive.md
docs/usage/creating-handlers.md
example-project/Directive.yaml

Atmo Beta-4.4 updates Reactr to Beta-15.1 and adds OpenTelemetry to Atmo Proxy.

chore: Release v0.4.4

---

.goreleaser.yml

chore: Disable arm64 builds

---

atmo/appsource/httpsource.go

Fixed Variable `url` conflicts with imported package 

---

atmo/appsource/vkrouter.go

variable `fqfn` conflicts with `fqfn` package is fixed

---

bundle/bundle.go

Fixed Variable `directive` conflicts with imported package

---

syncer/syncer.go

The current implementation introduces a fair amount of lock contention for what should be a read-heavy workload. 
This PR provides a small fix to provide some relief here until a more sophisticated implementation can be designed/implemented.

Proposal(syncer): More conservative locking on sync job

---

.github/renovate.json5

chore: Disable opentelemetry-go updates

---

sat/.goreleaser.yml
sat/Makefile

chore: Remove suborbital/wasmtime

---

.github/workflows/ci.yml

Remove duplicate image step and build/test image in the same step that
would release it for caching reasons.

chore: Add image tests

---

e2core/backend/satbackend/appsource.go
e2core/command/mod_start.go
e2core/command/start.go
e2core/server/server_test.go
foundation/bus/bus/options.go
foundation/scheduler/scheduler.go
sat/main.go

chore(e2core): Zerologs have timestamps, but not the tests

---

e2core/auth/access.go
e2core/auth/authorizer_test.go
e2core/server/handlers.go

validated against https://github.com/suborbital/se2/pull/1098

fix(Handler): Update tenant name resolution to match new api

---

sat/sat/sat.go

No issue
Sat shutdown should complete

chore(e2core): Log all the things on shutdown

---

go.mod
go.sum

Updates systemspec used to the version that has the error logging in it

fix(systemspec): Update systemspec and zerolog

---

go.mod
go.sum

Better error messaging from systemspec's httpsource authedget

fix(systemspec) Update systemspec version for better authendget error messages

---

go.mod
go.sum

Has the 10 second timeout in it

fix(systemspec): Update systemspec to 41f9f970
